const express = require('express');
const router = express.Router();
const multer = require('multer');
const OrderController = require('../controllers/order.controller');
const authMiddleware = require('../middleware/authMiddleware');
const InvoiceController = require('../controllers/invoice.controller');
const UpdateRemittanceController = require('../controllers/updateRemittance.controller.js');
// const { getShofifyData, getGoogleAnalyticsData } = require('../controllers/shopify.controller.js');
const storage = multer.memoryStorage();
const upload = multer({ storage });
const uploadMiddleware = upload.single('formData');

router.get('/get-orders', authMiddleware(), OrderController.getOrders);
router.post('/delayed-orders', authMiddleware(), OrderController.getDelayedOrders);
router.post('/delay-in-packing', authMiddleware(), OrderController.getDelayedInPackingOrders);
router.post('/open-tickets', authMiddleware(), OrderController.getOpenTickets);
router.post('/order-listing', authMiddleware(), OrderController.getFilteredOrders);
router.post('/order-overview', authMiddleware(), OrderController.orderOverview);
router.post('/Other-status-overview-Data', authMiddleware(), OrderController.OtherStatusOverviewData);
router.post('/order-count', authMiddleware(), OrderController.orderCount);
router.post('/ordersDeliveryPartner', authMiddleware(), OrderController.ordersDeliveryPartner);
router.post('/get-order-courier-partner', authMiddleware(), OrderController.getOrdersCourierPartner);
router.post('/get-order-courier-listing', authMiddleware(), OrderController.getOrdersCourierlisting);
router.post('/get-totalsales', authMiddleware('seller_admin'), UpdateRemittanceController.getTotalSales);
router.post('/update-remittance', authMiddleware('seller_admin'), UpdateRemittanceController.updateRemittance);
router.get('/list-of-distinct-state', authMiddleware(), OrderController.getDistinctState);
router.post('/analytics-data',authMiddleware(), OrderController.getAnalyticsData);
router.post('/get-pendency-funnel',authMiddleware(), OrderController.getPendencyFunnel);
router.post('/get-pendency-funnel-listing',authMiddleware(), OrderController.getPendencyOrdersListing);
router.post('/get-Otiff-Report',authMiddleware(), OrderController.getOtiffReport);
router.post('/get-pending-otiff-orders',authMiddleware(), OrderController.getPendingOtiffOrders);
router.post('/get-delayed-sbd-orders',authMiddleware(), OrderController.getDelayedSbdOrders).get('/get-delayed-sbd-orders', OrderController.getDelayedSbdOrders);
router.post('/get-order-by-status',authMiddleware(), OrderController.getOrdersByStatus);
router.post('/get-tickets-listing',authMiddleware(), OrderController.geTicketsListing);
router.get('/get-whatsapp-count', authMiddleware(), OrderController.getWhatsappCount);
router.get('/download-orders-count',OrderController.downloadOrdersCount);
router.get('/download-orders-listing',OrderController.downloadOrdersListing);
router.post('/get-rto-data',authMiddleware(), OrderController.getRtoData);
router.post('/get-rto-graph-data',authMiddleware(), OrderController.getRtoGraphData);
router.post('/get-rto-lm-graph-data',authMiddleware(), OrderController.getRtoLmGraphData);
router.post('/get-rto-status-data',authMiddleware(), OrderController.getStatusWiseRtoData);
router.get('/get-delays-data',authMiddleware(), OrderController.getDelaysData);
router.get('/download-rto-data', OrderController.downloadRTOData);
router.post('/upload-excel-data', authMiddleware('seller_admin'), uploadMiddleware, InvoiceController.uploadExcelData);
router.get('/get-last-remittance-date', authMiddleware(), UpdateRemittanceController.checkLastRemittanceDate);
// router.get('/shopify-checkouts', authMiddleware(), getShofifyData);
// router.get('/shopify-google-analytics', authMiddleware(), getGoogleAnalyticsData);
router.post('/brand-wise-sales', authMiddleware(), OrderController.getBrandwiseSalesSummary);
router.post('/get-purchase-grn-data', authMiddleware(), OrderController.getPurchaseGrnData);
router.post('/get-sales-analytics-data',authMiddleware(), OrderController.getSalesAnalyticsData);
router.post('/get-sales-sku-data',authMiddleware(), OrderController.getSalesSkuData);
// router.post('/get-sales-sku-summary',authMiddleware(), OrderController.getSalesSkuSummary);
router.post('/get-discount-graph',authMiddleware(), OrderController.getDiscountGraph);
router.post('/get-siens-orders',authMiddleware(), OrderController.getSiensOrders);
router.post('/get-siens-card-data', authMiddleware(), OrderController.getSiensCardData);
router.post('/get-siens-sku-summary', authMiddleware(), OrderController.getSiensSkuSummary);
router.get('/export-siens-orders', OrderController.exportSiensOrders);
router.get('/export-siens-sku-summary', OrderController.downloadSiensSkuSummaryReport);
router.get('/export-orders-data', OrderController.exportOrdersData);
router.post('/get-rto-analysis', authMiddleware(), OrderController.getRtoSummary);



module.exports = router;